services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    platform: linux/arm64
    restart: unless-stopped
    expose:
      - 9000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - storage:/app/storage:rw
      - public:/app/public:rw
    environment:
      APP_NAME: FashionApp
      APP_URL: http://fashion-lt.id.vn/
      APP_DEBUG: "true"
      DB_CONNECTION: ${DB_CONNECTION}
      APP_KEY: ${APP_KEY}
      APP_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # JWT Configurations
      JWT_SECRET: ${JWT_SECRET}
      JWT_TTL: ${JWT_TTL}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL}

      # Firebase & Google Cloud
      FIREBASE_CREDENTIALS: /app/firebase-auth.json
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      GOOGLE_APPLICATION_CREDENTIALS: /app/firebase-auth.json
    # depends_on:
    #   - db

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: php artisan queue:work --tries=3
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - storage:/app/storage:rw
      - public:/app/public:rw
  
  nginx:
    image: nginx:1.25-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - storage:/app/storage:rw
      - public:/app/public:ro
    depends_on:
        - app

  # db:
  #   image: postgres:15
  #   container_name: laravel_db
  #   restart: always
  #   environment:
  #     POSTGRES_DB: laravel 
  #     POSTGRES_USER: laravel
  #     POSTGRES_PASSWORD: secret
  #   volumes:
  #     - db_data:/var/lib/postgresql/data 
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - laravel

  # redis:
  #   image: redis:alpine
  #   container_name: laravel_redis
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - laravel

# volumes:
#   db_data:

# networks:
#   laravel:

volumes:
  storage:
  public:
  db-data:
  # redis-data:
